### ISSUE TITLE
Heatmap for markers in Tileview

### ISSUE THREAD

**Issue by android-bash** [HeartlandSoftware/AndroidHeatMap#8]
I have worked on indoormap project using https://github.com/moagrius/TileView library and i am showing markers for set of locations (x,y). Now i want to use heatmap on top of it. Any help?  

I tried using the library and i can display for random points but not for my (x,y) For ex : "x": 538.7601971900441, "y": 656.7830747555087

**Comment by tredpath** [comment]
x,y coordinates have to be specified as a percentage of the control dimensions. So if the control was 1000px by 1000px your example point would need added as (0.53876, 0.65678). Can you confirm this is how you are adding points?

**Comment by android-bash** [comment]
Thanks a lot for reply. I will get back to you. With your reply i feel i have chosen right library for heatmap. Great work.

**Comment by android-bash** [comment]
If i have an image of size 1825*1368 loaded in a Tileview (which is scrollable widthwise), then how do i set heatmap to cover (x,y) points on the Tileview image

**Comment by tredpath** [comment]
I don't know a lot about the TileView but it looks like the best way to do it would be to add a heat map that covers the entire TileView. Then you can add a [Listener](https://github.com/moagrius/TileView/blob/fa708a001389418b2d878eba5a06f487e4dc524a/tileview/src/main/java/com/qozix/tileview/TileView.java#L529) to that TileView so that you can manually reposition/clip the points and redraw them on the heat map so that they line up with the underlying TileView whenever the TileView is scrolled or scaled.
